# Generated by Django 3.1.7 on 2021-04-06 01:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('season', models.CharField(choices=[('AL', 'All'), ('WT', 'Winter'), ('SP', 'Spring'), ('SM', 'Summer'), ('FL', 'Fall')], max_length=10)),
                ('activity', models.CharField(default='', max_length=50, null=True)),
                ('travelers', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('season', models.CharField(choices=[('AL', 'All'), ('WT', 'Winter'), ('SP', 'Spring'), ('SM', 'Summer'), ('FL', 'Fall')], default='AL', max_length=10)),
                ('activity', models.CharField(choices=[('AL', 'All'), ('BP', 'Backpacking'), ('SS', 'Sightseeing'), ('LS', 'Leisure'), ('BS', 'Business'), ('OT', 'Other')], default='AL', max_length=10)),
                ('person', models.CharField(choices=[('A', 'All'), ('I', 'Infant'), ('C', 'Child'), ('T', 'Teen'), ('A', 'Adult'), ('S', 'Senior')], default='A', max_length=10)),
                ('gender', models.CharField(choices=[('A', 'All'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='A', max_length=10)),
                ('vote', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('CL', 'Clothing'), ('EL', 'Electronics'), ('EQ', 'Equipment'), ('PS', 'Personal'), ('MD', 'Medication'), ('OT', 'Other')], max_length=10)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vote'],
            },
        ),
    ]
