# Generated by Django 3.1.7 on 2021-04-07 15:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.CharField(default='All', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('season', models.CharField(choices=[('AL', 'All'), ('WT', 'Winter'), ('SP', 'Spring'), ('SM', 'Summer'), ('FL', 'Fall')], default='All', max_length=25)),
                ('activity', models.CharField(choices=[('AL', 'All'), ('BP', 'Backpacking'), ('BS', 'Business'), ('LS', 'Leisure'), ('SS', 'Sightseeing'), ('OT', 'Other')], default='All', max_length=25)),
                ('age', models.CharField(choices=[('A', 'All Ages'), ('I', 'Infant'), ('C', 'Child'), ('T', 'Teen'), ('A', 'Adult'), ('S', 'Senior')], default='All Ages', max_length=25)),
                ('gender', models.CharField(choices=[('A', 'All'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='All', max_length=25)),
                ('category', models.CharField(choices=[('CL', 'Clothing'), ('EL', 'Electronics'), ('EQ', 'Equipment'), ('PS', 'Personal'), ('MD', 'Medication'), ('OT', 'Other')], max_length=25)),
                ('trip_id', models.IntegerField(null=True)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('A', 'All'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='All', max_length=25)),
                ('age', models.CharField(choices=[('A', 'All Ages'), ('I', 'Infant'), ('C', 'Child'), ('T', 'Teen'), ('A', 'Adult'), ('S', 'Senior')], default='All Ages', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('season', models.CharField(choices=[('AL', 'All'), ('WT', 'Winter'), ('SP', 'Spring'), ('SM', 'Summer'), ('FL', 'Fall')], default='All', max_length=25)),
                ('number_items', models.IntegerField(default=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vote', models.IntegerField(default=0)),
                ('checked', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vote'],
            },
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='traveler',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.trip'),
        ),
        migrations.AddField(
            model_name='activity',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trip'),
        ),
    ]
