# Generated by Django 3.1.7 on 2021-04-07 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210406_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='activity',
        ),
        migrations.AlterField(
            model_name='item',
            name='activity',
            field=models.CharField(choices=[('AL', 'All'), ('BP', 'Backpacking'), ('BS', 'Business'), ('LS', 'Leisure'), ('SS', 'Sightseeing'), ('OT', 'Other')], default='All', max_length=25),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.CharField(default='All', max_length=50)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trip')),
            ],
        ),
    ]
