# Generated by Django 3.1.7 on 2021-04-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210404_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('season', models.CharField(choices=[('WT', 'Winter'), ('SP', 'Spring'), ('SM', 'Summer'), ('FL', 'Fall')], default='WT', max_length=2)),
                ('activity', models.CharField(choices=[('Au', 'Austin'), ('Lo', 'Logan'), ('Da', 'Daniel'), ('Mi', 'Mike'), ('Ma', 'Marielle'), ('Mi', 'Shirley')], default='Au', max_length=2)),
                ('vote', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.city')),
            ],
            options={
                'ordering': ['-vote'],
            },
        ),
    ]
