# Generated by Django 3.1.7 on 2021-04-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210406_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-vote']},
        ),
        migrations.AddField(
            model_name='item',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
