# Generated by Django 3.1.7 on 2021-04-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
