# Generated by Django 3.1.7 on 2021-04-04 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_auto_20210404_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='person',
            field=models.CharField(choices=[('Mn', 'Men'), ('Wm', 'Women'), ('By', 'Baby')], default='Mn', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
