# Generated by Django 3.1.7 on 2021-04-05 16:31

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_auto_20210404_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='acitivity',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='travelers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=50, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='city',
            name='trip_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='city',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='activity',
            field=models.CharField(choices=[('BP', 'Backpacking'), ('SS', 'Siteseeing'), ('LS', 'Leisure'), ('BS', 'Business')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='season',
            field=models.CharField(choices=[('WT', 'Winter'), ('SP', 'Spring'), ('SM', 'Summer'), ('FL', 'Fall')], max_length=2),
        ),
    ]
