# Generated by Django 3.1.7 on 2021-04-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210405_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='user_id',
            new_name='user',
        ),
    ]
