# Generated by Django 3.1.7 on 2021-04-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210405_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='acitivity',
            new_name='activity',
        ),
    ]
