# Generated by Django 3.1.7 on 2021-04-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210405_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='travelers',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
