# Generated by Django 3.1.7 on 2021-04-05 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210405_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_trip',
            name='trip',
        ),
        migrations.AddField(
            model_name='trip',
            name='my_trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.my_trip'),
            preserve_default=False,
        ),
    ]
