# Generated by Django 3.1.7 on 2021-04-05 18:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0012_auto_20210405_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(to='main_app.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='city',
            name='travelers',
        ),
        migrations.RemoveField(
            model_name='city',
            name='trip_date',
        ),
        migrations.RemoveField(
            model_name='city',
            name='user',
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('activity', models.CharField(default='', max_length=50, null=True)),
                ('travelers', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('my_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.my_trip')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
