# Generated by Django 3.1.7 on 2021-04-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210405_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_trip',
            name='item',
        ),
        migrations.AddField(
            model_name='my_trip',
            name='item',
            field=models.ManyToManyField(to='main_app.Item'),
        ),
    ]
