# Generated by Django 3.1.7 on 2021-04-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210405_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='my_trip',
        ),
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.CharField(default='Canada', max_length=50),
        ),
    ]
