# Generated by Django 3.1.7 on 2021-04-05 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_trip_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='name',
        ),
    ]
