# Generated by Django 3.1.7 on 2021-04-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20210405_1411'),
        ('main_app', '0015_remove_trip_name'),
    ]

    operations = [
    ]
