# Generated by Django 3.1.7 on 2021-04-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_merge_20210405_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CL', 'Clothings'), ('EL', 'Electronics'), ('EQ', 'Equipments'), ('PS', 'Personal'), ('MD', 'Medication'), ('OT', 'Others')], default='CL', max_length=2),
        ),
    ]
